spring:
  datasource:
    url: jdbc:h2:mem:db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform:
  h2:
    console:
      enabled: true
      path: /h2-console
  liquibase:


google:
  api-key: ${GOOGLE_API_TOKEN}
  query-rate-limit: 5